### PR TITLE
Plasticity cpp

### PR DESCRIPTION
**Pull request by ajafarihub**
Plasticity model with Von-Mises Yield surface and rate-independent history has been added. Tests on each of material and structural levels have been added, too.

### CODE REVIEW

**Comment by TTitscher** [comment]
I see some minor issues regarding code style (that I can try to fix). Beforehand: I know that @srosenbu did a lot of work on plasticity in (e.g) in [radial_return](https://github.com/BAMresearch/fenics-constitutive/tree/radial_return). How do they overlap?

**Comment by srosenbu** [comment]
@TTitscher ,
My code that might be compatible with this branch is on 
[new-plasticity](https://github.com/BAMresearch/fenics-constitutive/blob/new-plasticity/src/plasticity.h)
However, I abandoned the branch a little since I probably will only need radial return plasticity. It only works for 3D-Problems and testing is a little lacking....

I wouldn't want to try to make the radial return plasticity compatible with the "closest point projection" type. The Interfaces for yield functions are totally different. 

I will take some time the next days to look over it more closely, but I would like some features of my plasticity-branch to be present here. For example: having a general  Interface for a yield function instead of it being hardcoded for von mises plasticity.
@ajafarihub, maybe you could look over the code in my branch and think about whether we should combine some of it

**Comment by ajafarihub** [comment]
@TTitscher , from my point of view it is OK if you fix minor issues you see in the code.
@srosenbu I think , a good way  of finding similar stuff in your branch is to first have a look at a user-level code : how you use your library. For example, I have some classes for "rate-independent history" that I think you deal with it in some other way.

**Comment by srosenbu** [comment]
I would close this, since we don't work on the legacy version anymore

**Pull request closed without merging**
